"""Generate docs/support_matrix.md from the live rule registry and builder.

The support matrix is the honest-boundary artifact: what the engine checks,
at which severity, from which layer, and what each rule needs to be
definitive (UPF_ONLY / NETLIST_REQUIRED / PARTIAL). Regenerated by script so
the document cannot drift from the registry.

Usage:
    python scripts/generate_support_matrix.py            # write the doc
    python scripts/generate_support_matrix.py --verify   # exit 1 on drift
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from upf_insight import __version__  # noqa: E402
from upf_insight.engine.rules.rules_registry import registered_rules  # noqa: E402

DOC = ROOT / "docs" / "support_matrix.md"

LAYER_TITLES = {
    "SYNTAX": "Syntax & version",
    "REFERENCE": "Reference integrity",
    "SUPPLY_DOMAIN": "Supply & domain integrity",
    "SUPPLY": "Supply connectivity",
    "PST": "Power state table",
    "STRATEGY": "Strategy lint",
    "DESIGN": "Design-aware",
}

CONTEXT_NOTE = {
    "UPF_ONLY": "provable from the UPF alone",
    "NETLIST_REQUIRED": "needs netlist/RTL context - advisory without it",
    "PARTIAL": "structural evidence only",
}


def render() -> str:
    rules = registered_rules()
    lines = [
        "# UPF-Insight support matrix",
        "",
        f"Version: {__version__} · rules registered: {len(rules)} · "
        "engine: deterministic, no LLM in the analysis path.",
        "",
        "Honest boundary: **\"no errors\" does not mean \"power proven "
        "correct\"**. Rules with context NETLIST_REQUIRED or PARTIAL are "
        f"{CONTEXT_NOTE['NETLIST_REQUIRED']}.",
        "",
    ]
    contexts = Counter(r.context for r in rules)
    lines.append("Context distribution: "
                 + " · ".join(f"{k} {contexts.get(k, 0)}"
                              for k in sorted(contexts))
                 + "")
    layers = []
    for r in rules:
        if r.layer not in layers:
            layers.append(r.layer)
    for layer in layers:
        subset = [r for r in rules if r.layer == layer]
        title = LAYER_TITLES.get(layer, layer.title())
        lines += ["", f"## {title} ({layer}) — {len(subset)} rules", "",
                  "| Code | Sev | Context | Title |",
                  "|---|---|---|---|"]
        for r in subset:
            lines.append(f"| {r.code} | {r.severity} | {r.context} | "
                         f"{r.title} |")
    lines += ["", "## Supported UPF commands", ""]
    from upf_insight.model.builder import _SUPPORTED, _LEGAL_OPTIONS

    for cmd in sorted(_SUPPORTED):
        n = len(_LEGAL_OPTIONS.get(cmd, {}))
        opts = f" ({n} known options)" if n else ""
        lines.append(f"- `{cmd}`{opts}")
    unsupported_note = (
        "Commands outside this list are recorded as `unsupported_commands` "
        "in the model and surfaced honestly in the support boundary.")
    lines += ["", unsupported_note, ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--verify", action="store_true")
    args = ap.parse_args()
    text = render()
    if args.verify:
        if not DOC.exists() or DOC.read_text(encoding="utf-8") != text:
            print("support matrix stale; run: "
                  "python scripts/generate_support_matrix.py")
            return 1
        print(f"support matrix verified: {DOC}")
        return 0
    DOC.parent.mkdir(parents=True, exist_ok=True)
    DOC.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
