"""Generate docs/upf/RULES_REGISTRY.md from the live rule registry.

The rules registry is the engineering contract between the checker, the
reports, the workspace, and CI policy. It is generated rather than
hand-maintained so it cannot drift from the code — the previous hand-kept
copy documented 65 rules and omitted UPF-085..100 entirely.

Usage:
    python scripts/generate_rules_registry.py            # write the doc
    python scripts/generate_rules_registry.py --verify   # exit 1 on drift
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from upf_insight import __version__  # noqa: E402
from upf_insight.engine.rules.audit import audit_registry  # noqa: E402
from upf_insight.engine.rules.rules_registry import registered_rules  # noqa: E402
from upf_insight.engine.rules.upf_rules import RULE_HANDLERS  # noqa: E402

DOC = ROOT / "docs" / "upf" / "RULES_REGISTRY.md"

LAYER_TITLES = {
    "SYNTAX": "Syntax & version",
    "REFERENCE": "Reference integrity",
    "SUPPLY_DOMAIN": "Supply & domain integrity",
    "SUPPLY": "Supply connectivity",
    "PST": "Power state table",
    "STRATEGY": "Strategy lint",
    "DESIGN": "Design-aware",
}

CONTEXT_NOTE = {
    "UPF_ONLY": "provable from the UPF alone",
    "NETLIST_REQUIRED": "needs netlist/RTL context - advisory without it",
    "PARTIAL": "structural evidence only",
}


def _range(subset) -> str:
    """Render a code range like ``UPF-001..006``, or ``UPF-085`` if single."""
    codes = sorted(r.code for r in subset)
    if len(codes) == 1:
        return codes[0]
    lo, hi = codes[0].split("-")[1], codes[-1].split("-")[1]
    return f"{codes[0]}..{hi}"


def render() -> str:
    rules = registered_rules()
    codes = sorted(r.code for r in rules)
    gaps = []
    prev = None
    for c in codes:
        n = int(c.split("-")[1])
        if prev is not None and n != prev + 1:
            gaps.append(f"{prev + 1:03d}-{n - 1:03d}")
        prev = n
    gap_text = ", ".join(gaps) if gaps else "none"

    layers = []
    for r in rules:
        if r.layer not in layers:
            layers.append(r.layer)

    lines = [
        "# UPF-Insight - Rules Registry",
        "",
        "> **Document kind:** engineering contract - the canonical list of rule codes.",
        "> **Source of truth:** `upf_insight/engine/rules/rules_registry.py`",
        f"> **Generated by:** `scripts/generate_rules_registry.py` · "
        f"**Version:** v{__version__}",
        "",
        "---",
        "",
        "This document is generated from the registry module. Every rule has a "
        "stable code, a severity, a layer, a description, and a `test_ref` "
        "naming the regression test that proves it fires or stays quiet.",
        "",
        f"**{len(rules)} rules registered** · codes {codes[0]}..{codes[-1]} "
        f"with intentional gaps ({gap_text}). The gaps are unused code space "
        "reserved by the layered allocation, not missing rules.",
        "",
        "**Layer legend:** "
        + " · ".join(f"`{layer}`" for layer in layers),
        "",
        "**Context legend:** "
        + " · ".join(f"`{k}` ({v})" for k, v in CONTEXT_NOTE.items()),
        "",
        "Every registered rule has a handler: `upf-insight rules audit` and "
        "`tests/test_rule_audit.py` both enforce registry/handler equality, so "
        "there are no dormant codes. A rule whose handler raises is reported "
        "as an internal error with `support=NOT_VALIDATED` - the engine never "
        "lets a crashed rule read as a clean bill of health.",
        "",
    ]

    for layer in layers:
        subset = [r for r in rules if r.layer == layer]
        title = LAYER_TITLES.get(layer, layer.title())
        lines += [
            f"## {title} ({layer}) - {_range(subset)}",
            "",
            "| Code | Severity | Context | Title | Description |",
            "|---|---|---|---|---|",
        ]
        for r in subset:
            lines.append(
                f"| {r.code} | {r.severity} | `{r.context}` | {r.title} | "
                f"{r.description} |"
            )
        lines.append("")

    lines += [
        "## Verification",
        "",
        "```bash",
        "upf-insight rules audit          # registry/handler sync, must be clean",
        "upf-insight rules list           # every code with severity and context",
        "python -m pytest tests/test_rule_audit.py -q",
        "```",
        "",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--verify", action="store_true",
                    help="exit 1 if the document is out of date")
    args = ap.parse_args()

    report = audit_registry()
    if not report["clean"]:
        print("registry audit failed; fix this before documenting it:",
              file=sys.stderr)
        for p in report["problems"]:
            print(f"  - {p}", file=sys.stderr)
        return 1

    text = render()
    if args.verify:
        if not DOC.exists() or DOC.read_text(encoding="utf-8") != text:
            print(f"{DOC} is out of date; run without --verify", file=sys.stderr)
            return 1
        print(f"{DOC.name}: up to date ({len(RULE_HANDLERS)} handlers)")
        return 0

    DOC.parent.mkdir(parents=True, exist_ok=True)
    DOC.write_text(text, encoding="utf-8")
    print(f"wrote {DOC} ({len(registered_rules())} rules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
